[project]
name = "m4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "numpy>=2.0.2",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.6.1",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "shap>=0.46.0",
    "statsmodels>=0.14.6",
    "tqdm>=4.67.1",
    "xgboost>=2.1.4",
]

[dependency-groups]
dev = [
    "black>=25.11.0",
    "flake8>=7.3.0",
    "ipykernel>=6.31.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.2",
    "pre-commit>=4.3.0",
    "tabulate>=0.9.0",
    "ydata-profiling>=4.17.0",
]
